project:
  type: website
  resources: ["ex1defense.png"]

website:
  title: "3 pointer Project"
  navbar:
    left:
      - href: blah.qmd
        text: Home
      - about.qmd

format:
  closeread-html:
    cr-style:
      section-background-color: "#FFFFFF"
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

